# Makes the builder image, takes about 20 min to build and compile on default hardware
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'run', '--privileged', 'linuxkit/binfmt:v0.7' ]
    id: 'initialize-qemu'
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'buildx', 'create', '--name', 'mybuilder' ]
    id: 'create-builder'
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'buildx', 'use', 'mybuilder' ]
    id: 'select-builder'
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'buildx','inspect', '--bootstrap' ]
    id: 'show-target-build-platforms'
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'buildx','build','--platform', '${_DOCKER_BUILDX_PLATFORMS}', '-t', '${_IMAGE_FULL_NAME}:latest', '-t', '${_IMAGE_FULL_NAME}:${SHORT_SHA}', '--push', '.' ]
    id: 'build-multi-architecture-container-image'
timeout: 3600s  # Takes some time to download and compile
options:
  machineType: E2_HIGHCPU_8  # About 10 minutes with better hardware
  dynamic_substitutions: true
  env:
    - DOCKER_CLI_EXPERIMENTAL=enabled
substitutions:
  _DOCKER_BUILDX_PLATFORMS: 'linux/amd64,linux/arm64'
  _IMAGE_FULL_NAME: us-central1-docker.pkg.dev/ox-lab-anthony-molinaro/test-artifacts/cloudbuild-test
